
global:
  smtp_smarthost: ${SMTP_HOST}
  smtp_from: ${SMTP_FROM_ADDRESS}
  smtp_auth_username: ${SMTP_USER}
  smtp_auth_password: ${SMTP_PASSWORD}

route:
  receiver: 'email-alerts'

receivers:
  - name: 'email-alerts'
    email_configs:
      - to: ${PRIMARY_RECIPIENT}
        send_resolved: true