global:
  scrape_interval: 5s

# alerting:
#   alertmanagers:
#     - static_configs:
#       - targets: ['alertmanager:9093']
scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9090']
        labels:
          instance: 'otel-collector'
          Application: 'otel-collector'
  - job_name: 'loki'
    metrics_path: /metrics
    static_configs:
      - targets: ['loki:3100']
        labels:
          instance: 'loki'
          Application: 'loki'
  - job_name: 'app'
    metrics_path: /metrics
    static_configs:
      - targets: ['app:4000']
        labels:
          instance: 'app-nodejs'
          Application: 'app-nodejs'


# rule_files:
#   - "rules/alert-rule.yml"